version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.8    
      
    - image: circleci/mysql:8.0.12
      command: |
          mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
      

    working_directory: ~/repo



    steps:
      - checkout
      
      - run:
          command:
            pip install -r requirements.txt
      
      - run:
          command:
            python manage.py makemigrations

      - run:
          command:
            python manage.py migrate
     
      - run:
          name: Running tests
          command:
            python manage.py test

      - store_artifacts:
          path: test-reports/
          destination: python_app